name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build APK with Bubblewrap
        uses: Nico04/bubblewrap-action@v1
        with:
          url: 'https://tu-usuario.github.io/tu-repo/' # Aquí necesitas tener activado GitHub Pages
          appName: 'AleGamePad Tester'
