name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4 # Actualizado a v4

      - name: Build Android APK
        uses: unaty/html-to-apk-action@v1.1 # Asegúrate de que esta versión sea la correcta
        with:
          app-name: "AleGamePad Tester"
          # Si no tienes un icono llamado icon.png, elimina la línea de abajo
          # icon: "icon.png" 

      - name: Upload APK
        uses: actions/upload-artifact@v4 # Actualizado a v4
        with:
          name: gamepad-tester-apk
          path: ./*.apk
